#!/usr/bin/env python3
"""
Generate a 12x12 CJK bitmap font header (cjk_glyphs.h) for the XiaoMiao ESP32
Marauder. Renders GB2312 Level-1 common-use Hanzi (3755 chars) plus fullwidth
punctuation from the system SimHei font via Pillow, packing each glyph as 24
bytes (12 rows x 12 bits = 2 bytes/row). Also emits a sorted (codepoint, index)
table for O(log n) lookup and a drawCJKChar() implementation.

Output: esp32_marauder/cjk_glyphs.h

Usage: python tools_local/gen_cjk_font.py
"""
import sys
import struct

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    print("ERROR: Pillow is required. Install: pip install pillow", file=sys.stderr)
    sys.exit(1)

# GB2312 Level-1 range: 0xB0A1 .. 0xF7FE (rows B0-F7, cols A1-FE)
# These are the 3755 "common use" Hanzi sorted by pinyin/stroke.
def gb2312_level1_codepoints():
    """Yield Unicode codepoints for GB2312 Level-1 Hanzi in order."""
    cps = []
    for row in range(0xB0, 0xF8):       # B0-F7
        for col in range(0xA1, 0xFF):    # A1-FE
            try:
                gb_bytes = bytes([row, col])
                cp = gb_bytes.decode('gb2312')
                cps.append((ord(cp), row, col))
            except (UnicodeDecodeError, ValueError):
                continue
    return cps

FONT_PATHS = [
    "C:/Windows/Fonts/simhei.ttf",
    "C:/Windows/Fonts/msyh.ttc",
    "C:/Windows/Fonts/simsun.ttc",
]

GLYPH_W = 12
GLYPH_H = 12

def render_glyph(font, codepoint):
    """Render a single codepoint to a 12x12 bitmap. Returns 24 bytes (2 per row)."""
    img = Image.new('L', (GLYPH_W, GLYPH_H), 0)
    draw = ImageDraw.Draw(img)
    ch = chr(codepoint)
    # Get glyph bounding box to center it
    bbox = draw.textbbox((0, 0), ch, font=font)
    w = bbox[2] - bbox[0]
    h = bbox[3] - bbox[1]
    x_off = (GLYPH_W - w) // 2 - bbox[0]
    y_off = (GLYPH_H - h) // 2 - bbox[1]
    draw.text((x_off, y_off), ch, fill=255, font=font)

    pixels = img.load()
    packed = bytearray(GLYPH_H * 2)  # 2 bytes per row (12 bits + 4 padding)
    for row in range(GLYPH_H):
        bits = 0
        for col in range(GLYPH_W):
            if pixels[col, row] > 127:
                bits |= (1 << (15 - col))
        packed[row * 2] = (bits >> 8) & 0xFF
        packed[row * 2 + 1] = bits & 0xFF
    return bytes(packed)

def main():
    # Load font
    font = None
    for fp in FONT_PATHS:
        try:
            font = ImageFont.truetype(fp, 12)
            print(f"Using font: {fp}", file=sys.stderr)
            break
        except Exception:
            continue
    if font is None:
        print("ERROR: No CJK font found", file=sys.stderr)
        sys.exit(1)

    # Also include common ASCII + fullwidth punctuation codepoints that appear in SSIDs
    extra_cps = []
    # Common SSID punctuation already in ASCII font, skip those.
    # Add fullwidth digits/letters/space that sometimes appear
    for cp in list(range(0xFF01, 0xFF5F)):  # fullwidth punctuation
        extra_cps.append(cp)

    cps = gb2312_level1_codepoints()
    all_cps = [(cp, r, c) for cp, r, c in cps] + [(cp, 0, 0) for cp in extra_cps]
    # Sort by codepoint for binary search
    all_cps.sort(key=lambda x: x[0])

    print(f"Total glyphs to render: {len(all_cps)}", file=sys.stderr)

    # Render all glyphs
    bitmaps = []
    codepoints = []
    for i, (cp, _, _) in enumerate(all_cps):
        bm = render_glyph(font, cp)
        bitmaps.append(bm)
        codepoints.append(cp)
        if (i + 1) % 500 == 0:
            print(f"  rendered {i+1}/{len(all_cps)}", file=sys.stderr)

    # Write header file
    out_path = "esp32_marauder/cjk_glyphs.h"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by tools_local/gen_cjk_font.py — DO NOT EDIT\n")
        f.write("// 12x12 CJK bitmap font (GB2312 Level-1 + fullwidth punctuation)\n")
        f.write(f"// {len(codepoints)} glyphs, {len(codepoints) * 24} bytes bitmap data\n")
        f.write("#pragma once\n")
        f.write("#include <Arduino.h>\n\n")

        # Bitmap data
        f.write(f"static const uint8_t CJK_BITMAPS[{len(codepoints)}][24] PROGMEM = {{\n")
        for i, bm in enumerate(bitmaps):
            hex_vals = ','.join(f'0x{b:02X}' for b in bm)
            f.write(f"  {{{hex_vals}}}")
            if i < len(bitmaps) - 1:
                f.write(",")
            f.write("\n")
        f.write("};\n\n")

        # Sorted codepoint table for binary search
        f.write(f"static const uint16_t CJK_CODEPOINTS[{len(codepoints)}] PROGMEM = {{\n")
        for i in range(0, len(codepoints), 12):
            chunk = codepoints[i:i+12]
            vals = ','.join(f'0x{cp:04X}' for cp in chunk)
            f.write(f"  {vals}")
            if i + 12 < len(codepoints):
                f.write(",")
            f.write("\n")
        f.write("};\n\n")

        # Lookup function: binary search, returns index or -1
        f.write("static int16_t cjkLookup(uint16_t cp) {\n")
        f.write(f"  int16_t lo = 0, hi = {len(codepoints) - 1};\n")
        f.write("  while (lo <= hi) {\n")
        f.write("    int16_t mid = (lo + hi) / 2;\n")
        f.write("    uint16_t midCp = pgm_read_word(&CJK_CODEPOINTS[mid]);\n")
        f.write("    if (midCp == cp) return mid;\n")
        f.write("    if (midCp < cp) lo = mid + 1;\n")
        f.write("    else hi = mid - 1;\n")
        f.write("  }\n")
        f.write("  return -1;\n")
        f.write("}\n\n")

        # Draw function: renders a 12x12 CJK glyph at (x,y)
        f.write("// Draw a 12x12 CJK glyph. Returns glyph width (13 = 12px + 1px spacing).\n")
        f.write("// Call from TFT_eSPI drawChar when uniCode is in CJK range.\n")
        f.write("static int16_t drawCJKChar(uint16_t uniCode, int32_t x, int32_t y,\n")
        f.write("                          uint16_t color, uint16_t bg) {\n")
        f.write("  int16_t idx = cjkLookup(uniCode);\n")
        f.write("  if (idx < 0) return 6; // fallback: treat as unknown, advance like ASCII\n")
        f.write("  for (int row = 0; row < 12; row++) {\n")
        f.write("    uint8_t hi = pgm_read_byte(&CJK_BITMAPS[idx][row * 2]);\n")
        f.write("    uint8_t lo = pgm_read_byte(&CJK_BITMAPS[idx][row * 2 + 1]);\n")
        f.write("    uint16_t bits = (hi << 8) | lo;\n")
        f.write("    for (int col = 0; col < 12; col++) {\n")
        f.write("      if (bits & (1 << (15 - col)))\n")
        f.write("        tft_DrawPixel(x + col, y + row, color);\n")
        f.write("      else if (bg != color)\n")
        f.write("        tft_DrawPixel(x + col, y + row, bg);\n")
        f.write("    }\n")
        f.write("  }\n")
        f.write("  return 13; // advance width\n")
        f.write("}\n")

    total_bytes = len(codepoints) * 24 + len(codepoints) * 2
    print(f"Generated {out_path}: {len(codepoints)} glyphs, ~{total_bytes} bytes", file=sys.stderr)

if __name__ == "__main__":
    main()
